In [52]:
import pandas as pd
pd.options.display.max_columns = 99

# Explore the dataset

In [53]:
df = pd.read_csv('loans_2007.csv', nrows=3)
df

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,chargeoff_within_12_mths,delinq_amnt,pub_rec_bankruptcies,tax_liens
0,1077501,1296599.0,5000.0,5000.0,4975.0,36 months,10.65%,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-2011,Fully Paid,n,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-1985,1.0,3.0,0.0,13648.0,83.7%,9.0,f,0.0,0.0,5863.155187,5833.84,5000.00,863.16,0.0,0.00,0.00,Jan-2015,171.62,Jun-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
1,1077430,1314167.0,2500.0,2500.0,2500.0,60 months,15.27%,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-2011,Charged Off,n,car,bike,309xx,GA,1.00,0.0,Apr-1999,5.0,3.0,0.0,1687.0,9.4%,4.0,f,0.0,0.0,1008.710000,1008.71,456.46,435.17,0.0,117.08,1.11,Apr-2013,119.66,Sep-2013,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
2,1077175,1313524.0,2400.0,2400.0,2400.0,36 months,15.96%,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-2011,Fully Paid,n,small_business,real estate business,606xx,IL,8.72,0.0,Nov-2001,2.0,2.0,0.0,2956.0,98.5%,10.0,f,0.0,0.0,3005.666844,3005.67,2400.00,605.67,0.0,0.00,0.00,Jun-2014,649.91,Jun-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0

# Objectives
- For each chunk:   
    - How many columns have a numeric type? 
    - How many columns have a string type?
    - How many unique values are there in each string column? 
    - How many of the string columns contain values that are less than 50% unique?
    - Which float columns have no missing values and could be candidates for conversion to the integer type?
- Calculate the total memory usage across all of the chunks

In [54]:
chunk_iter = pd.read_csv('loans_2007.csv', chunksize=3000)

total_memory = 0.0
for chunk in chunk_iter:
    # Memory usage in MB
    memory = chunk.memory_usage(deep=True).sum()/(1024*1024)
    total_memory += memory
    
    # How many columns have a numeric type?
    ntype_col_count = chunk.select_dtypes(include='number').columns.size
    print('Num. of numeric type columns:', ntype_col_count, '\n')
    
    # How many columns have a string type?
    stype_col_count = chunk.select_dtypes(include='object').columns.size
    print('Num. of string type columns:', stype_col_count, '\n')
    
    # How many unique values are there in each string column?
    stype_unq_counts = chunk.select_dtypes(include='object').nunique()
    print('Unique values in each string type column:\n')
    print(stype_unq_counts)
    
    # How many of the string columns contain values that are less than 50% unique?
    print('\nString type columns containing values that are less than 50% unique:\n')
    string_type_cols = chunk.select_dtypes(include='object')
    for colname, colvalues in string_type_cols.iteritems():
        if colvalues.nunique() < colvalues.count()/2:
            print(colname)

    # Which float columns have no missing values?
    print('\nFloating type columns with no missing values:\n')
    col_na_count = chunk.select_dtypes(include='floating').isna().sum()
    for col in col_na_count.where(col_na_count == 0).index:
        print(col)
    
    print('\n' + '='*50 + '\n')
    

print('Total memory usage (MB) =', total_memory)

Num. of numeric type columns: 31

Num. of string type columns: 21

Unique values in each string type column:

term                      2
int_rate                 36
grade                     7
sub_grade                35
emp_title              2653
emp_length               11
home_ownership            3
verification_status       3
issue_d                   2
loan_status               6
pymnt_plan                1
purpose                  13
title                  1406
zip_code                568
addr_state               43
earliest_cr_line        366
revol_util              884
initial_list_status       1
last_pymnt_d             54
last_credit_pull_d       55
application_type          1
dtype: int64

String type columns containing values that are less than 50% unique:

term
int_rate
grade
sub_grade
emp_length
home_ownership
verification_status
issue_d
loan_status
pymnt_plan
purpose
title
zip_code
addr_state
earliest_cr_line
revol_util
initial_list_status
last_pymnt_d
last_credit_pull_d
application_type

Floating type columns with no missing values:

member_id
loan_amnt
funded_amnt
funded_amnt_inv
installment
annual_inc
dti
delinq_2yrs
inq_last_6mths
open_acc
pub_rec
revol_bal
total_acc
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_amnt
collections_12_mths_ex_med
policy_code
acc_now_delinq
chargeoff_within_12_mths
delinq_amnt
pub_rec_bankruptcies
tax_liens

==================================================

Num. of numeric type columns: 31

Num. of string type columns: 21

Unique values in each string type column:

term                      2
int_rate                 36
grade                     7
sub_grade                35
emp_title              2588
emp_length               11
home_ownership            3
verification_status       3
issue_d                   3
loan_status               6
pymnt_plan                1
purpose                  13
title                  1454
zip_code                570
addr_state               45
earliest_cr_line        399
revol_util              951
initial_list_status       1
last_pymnt_d             56
last_credit_pull_d       57
application_type          1
dtype: int64

String type columns containing values that are less than 50% unique:

term
int_rate
grade
sub_grade
emp_length
home_ownership
verification_status
issue_d
loan_status
pymnt_plan
purpose
title
zip_code
addr_state
earliest_cr_line
revol_util
initial_list_status
last_pymnt_d
last_credit_pull_d
application_type

Floating type columns with no missing values:

member_id
loan_amnt
funded_amnt
funded_amnt_inv
installment
annual_inc
dti
delinq_2yrs
inq_last_6mths
open_acc
pub_rec
revol_bal
total_acc
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_amnt
collections_12_mths_ex_med
policy_code
acc_now_delinq
chargeoff_within_12_mths
delinq_amnt
pub_rec_bankruptcies
tax_liens

==================================================

Num. of numeric type columns: 31

Num. of string type columns: 21

Unique values in each string type column:

term                      2
int_rate                 66
grade                     7
sub_grade                34
emp_title              2592
emp_length               11
home_ownership            3
verification_status       3
issue_d                   3
loan_status               5
pymnt_plan                1
purpose                  13
title                  1464
zip_code                571
addr_state               43
earliest_cr_line        401
revol_util              951
initial_list_status       1
last_pymnt_d             57
last_credit_pull_d       59
application_type          1
dtype: int64

String type columns containing values that are less than 50% unique:

term
int_rate
grade
sub_grade
emp_length
home_ownership
verification_status
issue_d
loan_status
pymnt_plan
purpose
title
zip_code
addr_state
earliest_cr_line
revol_util
initial_list_status
last_pymnt_d
last_credit_pull_d
application_type

Floating type columns with no missing values:

member_id
loan_amnt
funded_amnt
funded_amnt_inv
installment
annual_inc
dti
delinq_2yrs
inq_last_6mths
open_acc
pub_rec
revol_bal
total_acc
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_amnt
collections_12_mths_ex_med
policy_code
acc_now_delinq
chargeoff_within_12_mths
delinq_amnt
pub_rec_bankruptcies
tax_liens

==================================================

Num. of numeric type columns: 31

Num. of string type columns: 21

Unique values in each string type column:

term                      2
int_rate                 37
grade                     7
sub_grade                35
emp_title              2598
emp_length               11
home_ownership            3
verification_status       3
issue_d                   3
loan_status               6
pymnt_plan                1
purpose                  13
title                  1511
zip_code                559
addr_state               43
earliest_cr_line        383
revol_util              939
initial_list_status       1
last_pymnt_d             59
last_credit_pull_d       59
application_type          1
dtype: int64

String type columns containing values that are less than 50% unique:

term
int_rate
grade
sub_grade
emp_length
home_ownership
verification_status
issue_d
loan_status
pymnt_plan
purpose
zip_code
addr_state
earliest_cr_line
revol_util
initial_list_status
last_pymnt_d
last_credit_pull_d
application_type

Floating type columns with no missing values:

member_id
loan_amnt
funded_amnt
funded_amnt_inv
installment
annual_inc
dti
delinq_2yrs
inq_last_6mths
open_acc
pub_rec
revol_bal
total_acc
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_amnt
collections_12_mths_ex_med
policy_code
acc_now_delinq
chargeoff_within_12_mths
delinq_amnt
pub_rec_bankruptcies
tax_liens

==================================================

Num. of numeric type columns: 31

Num. of string type columns: 21

Unique values in each string type column:

term                      2
int_rate                 73
grade                     7
sub_grade                35
emp_title              2590
emp_length               11
home_ownership            4
verification_status       3
issue_d                   3
loan_status               6
pymnt_plan                1
purpose                  13
title                  1610
zip_code                568
addr_state               43
earliest_cr_line        391
revol_util              949
initial_list_status       1
last_pymnt_d             60
last_credit_pull_d       61
application_type          1
dtype: int64

String type columns containing values that are less than 50% unique:

term
int_rate
grade
sub_grade
emp_length
home_ownership
verification_status
issue_d
loan_status
pymnt_plan
purpose
zip_code
addr_state
earliest_cr_line
revol_util
initial_list_status
last_pymnt_d
last_credit_pull_d
application_type

Floating type columns with no missing values:

member_id
loan_amnt
funded_amnt
funded_amnt_inv
installment
annual_inc
dti
delinq_2yrs
inq_last_6mths
open_acc
pub_rec
revol_bal
total_acc
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_amnt
collections_12_mths_ex_med
policy_code
acc_now_delinq
chargeoff_within_12_mths
delinq_amnt
pub_rec_bankruptcies
tax_liens

==================================================

Num. of numeric type columns: 31

Num. of string type columns: 21

Unique values in each string type column:

term                      2
int_rate                 68
grade                     7
sub_grade                35
emp_title              2648
emp_length               11
home_ownership            3
verification_status       3
issue_d                   3
loan_status               4
pymnt_plan                1
purpose                  13
title                  1775
zip_code                578
addr_state               43
earliest_cr_line        383
revol_util              956
initial_list_status       1
last_pymnt_d             62
last_credit_pull_d       62
application_type          1
dtype: int64

String type columns containing values that are less than 50% unique:

term
int_rate
grade
sub_grade
emp_length
home_ownership
verification_status
issue_d
loan_status
pymnt_plan
purpose
zip_code
addr_state
earliest_cr_line
revol_util
initial_list_status
last_pymnt_d
last_credit_pull_d
application_type

Floating type columns with no missing values:

member_id
loan_amnt
funded_amnt
funded_amnt_inv
installment
annual_inc
dti
delinq_2yrs
inq_last_6mths
open_acc
pub_rec
revol_bal
total_acc
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_amnt
collections_12_mths_ex_med
policy_code
acc_now_delinq
chargeoff_within_12_mths
delinq_amnt
pub_rec_bankruptcies
tax_liens

==================================================

Num. of numeric type columns: 31

Num. of string type columns: 21

Unique values in each string type column:

term                      2
int_rate                 45
grade                     7
sub_grade                35
emp_title              2600
emp_length               11
home_ownership            3
verification_status       3
issue_d                   4
loan_status               4
pymnt_plan                1
purpose                  13
title                  1958
zip_code                551
addr_state               43
earliest_cr_line        385
revol_util              948
initial_list_status       1
last_pymnt_d             64
last_credit_pull_d       65
application_type          1
dtype: int64

String type columns containing values that are less than 50% unique:

term
int_rate
grade
sub_grade
emp_length
home_ownership
verification_status
issue_d
loan_status
pymnt_plan
purpose
zip_code
addr_state
earliest_cr_line
revol_util
initial_list_status
last_pymnt_d
last_credit_pull_d
application_type

Floating type columns with no missing values:

member_id
loan_amnt
funded_amnt
funded_amnt_inv
installment
annual_inc
dti
delinq_2yrs
inq_last_6mths
open_acc
pub_rec
revol_bal
total_acc
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_amnt
collections_12_mths_ex_med
policy_code
acc_now_delinq
chargeoff_within_12_mths
delinq_amnt
pub_rec_bankruptcies
tax_liens

==================================================

Num. of numeric type columns: 31

Num. of string type columns: 21

Unique values in each string type column:

term                      2
int_rate                 65
grade                     7
sub_grade                35
emp_title              2497
emp_length               11
home_ownership            3
verification_status       3
issue_d                   3
loan_status               3
pymnt_plan                1
purpose                  13
title                  1919
zip_code                558
addr_state               43
earliest_cr_line        387
revol_util              952
initial_list_status       1
last_pymnt_d             65
last_credit_pull_d       67
application_type          1
dtype: int64

String type columns containing values that are less than 50% unique:

term
int_rate
grade
sub_grade
emp_length
home_ownership
verification_status
issue_d
loan_status
pymnt_plan
purpose
zip_code
addr_state
earliest_cr_line
revol_util
initial_list_status
last_pymnt_d
last_credit_pull_d
application_type

Floating type columns with no missing values:

member_id
loan_amnt
funded_amnt
funded_amnt_inv
installment
annual_inc
dti
delinq_2yrs
inq_last_6mths
open_acc
pub_rec
revol_bal
total_acc
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_amnt
collections_12_mths_ex_med
policy_code
acc_now_delinq
chargeoff_within_12_mths
delinq_amnt
pub_rec_bankruptcies
tax_liens

==================================================

Num. of numeric type columns: 31

Num. of string type columns: 21

Unique values in each string type column:

term                      2
int_rate                 68
grade                     7
sub_grade                35
emp_title              2660
emp_length               11
home_ownership            3
verification_status       3
issue_d                   4
loan_status               4
pymnt_plan                2
purpose                  14
title                  1881
zip_code                555
addr_state               43
earliest_cr_line        374
revol_util              958
initial_list_status       1
last_pymnt_d             66
last_credit_pull_d       70
application_type          1
dtype: int64

String type columns containing values that are less than 50% unique:

term
int_rate
grade
sub_grade
emp_length
home_ownership
verification_status
issue_d
loan_status
pymnt_plan
purpose
zip_code
addr_state
earliest_cr_line
revol_util
initial_list_status
last_pymnt_d
last_credit_pull_d
application_type

Floating type columns with no missing values:

member_id
loan_amnt
funded_amnt
funded_amnt_inv
installment
annual_inc
dti
delinq_2yrs
inq_last_6mths
open_acc
pub_rec
revol_bal
total_acc
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_amnt
collections_12_mths_ex_med
policy_code
acc_now_delinq
chargeoff_within_12_mths
delinq_amnt
pub_rec_bankruptcies
tax_liens

==================================================

Num. of numeric type columns: 31

Num. of string type columns: 21

Unique values in each string type column:

term                      2
int_rate                 50
grade                     7
sub_grade                34
emp_title              2654
emp_length               11
home_ownership            3
verification_status       3
issue_d                   4
loan_status               2
pymnt_plan                1
purpose                  14
title                  2139
zip_code                524
addr_state               42
earliest_cr_line        367
revol_util              942
initial_list_status       1
last_pymnt_d             65
last_credit_pull_d       72
application_type          1
dtype: int64

String type columns containing values that are less than 50% unique:

term
int_rate
grade
sub_grade
emp_length
home_ownership
verification_status
issue_d
loan_status
pymnt_plan
purpose
zip_code
addr_state
earliest_cr_line
revol_util
initial_list_status
last_pymnt_d
last_credit_pull_d
application_type

Floating type columns with no missing values:

member_id
loan_amnt
funded_amnt
funded_amnt_inv
installment
annual_inc
dti
delinq_2yrs
inq_last_6mths
open_acc
pub_rec
revol_bal
total_acc
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_amnt
collections_12_mths_ex_med
policy_code
acc_now_delinq
chargeoff_within_12_mths
delinq_amnt
pub_rec_bankruptcies
tax_liens

==================================================

Num. of numeric type columns: 31

Num. of string type columns: 21

Unique values in each string type column:

term                      2
int_rate                 60
grade                     7
sub_grade                34
emp_title              2644
emp_length               11
home_ownership            4
verification_status       3
issue_d                   5
loan_status               2
pymnt_plan                1
purpose                  14
title                  2425
zip_code                527
addr_state               41
earliest_cr_line        363
revol_util              948
initial_list_status       1
last_pymnt_d             53
last_credit_pull_d       77
application_type          1
dtype: int64

String type columns containing values that are less than 50% unique:

term
int_rate
grade
sub_grade
emp_length
home_ownership
verification_status
issue_d
loan_status
pymnt_plan
purpose
zip_code
addr_state
earliest_cr_line
revol_util
initial_list_status
last_pymnt_d
last_credit_pull_d
application_type

Floating type columns with no missing values:

member_id
loan_amnt
funded_amnt
funded_amnt_inv
installment
annual_inc
dti
delinq_2yrs
inq_last_6mths
open_acc
pub_rec
revol_bal
total_acc
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_amnt
collections_12_mths_ex_med
policy_code
acc_now_delinq
chargeoff_within_12_mths
delinq_amnt
pub_rec_bankruptcies
tax_liens

==================================================

Num. of numeric type columns: 31

Num. of string type columns: 21

Unique values in each string type column:

term                      1
int_rate                 65
grade                     7
sub_grade                35
emp_title              2554
emp_length               11
home_ownership            4
verification_status       3
issue_d                   7
loan_status               2
pymnt_plan                1
purpose                  14
title                  2335
zip_code                538
addr_state               42
earliest_cr_line        373
revol_util              950
initial_list_status       1
last_pymnt_d             50
last_credit_pull_d       83
application_type          1
dtype: int64

String type columns containing values that are less than 50% unique:

term
int_rate
grade
sub_grade
emp_length
home_ownership
verification_status
issue_d
loan_status
pymnt_plan
purpose
zip_code
addr_state
earliest_cr_line
revol_util
initial_list_status
last_pymnt_d
last_credit_pull_d
application_type

Floating type columns with no missing values:

member_id
loan_amnt
funded_amnt
funded_amnt_inv
installment
annual_inc
dti
delinq_2yrs
inq_last_6mths
open_acc
pub_rec
revol_bal
total_acc
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_amnt
collections_12_mths_ex_med
policy_code
acc_now_delinq
chargeoff_within_12_mths
delinq_amnt
pub_rec_bankruptcies
tax_liens

==================================================

Num. of numeric type columns: 31

Num. of string type columns: 21

Unique values in each string type column:

term                      1
int_rate                107
grade                     7
sub_grade                35
emp_title              2598
emp_length               11
home_ownership            4
verification_status       3
issue_d                  17
loan_status               2
pymnt_plan                1
purpose                  14
title                  2297
zip_code                574
addr_state               47
earliest_cr_line        366
revol_util              929
initial_list_status       1
last_pymnt_d             59
last_credit_pull_d       97
application_type          1
dtype: int64

String type columns containing values that are less than 50% unique:

term
int_rate
grade
sub_grade
emp_length
home_ownership
verification_status
issue_d
loan_status
pymnt_plan
purpose
zip_code
addr_state
earliest_cr_line
revol_util
initial_list_status
last_pymnt_d
last_credit_pull_d
application_type

Floating type columns with no missing values:

member_id
loan_amnt
funded_amnt
funded_amnt_inv
installment
annual_inc
dti
delinq_2yrs
inq_last_6mths
open_acc
pub_rec
revol_bal
total_acc
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_amnt
collections_12_mths_ex_med
policy_code
acc_now_delinq
chargeoff_within_12_mths
delinq_amnt
pub_rec_bankruptcies
tax_liens

==================================================

Num. of numeric type columns: 30

Num. of string type columns: 22

Unique values in each string type column:

id                     3000
term                      2
int_rate                262
grade                     7
sub_grade                35
emp_title              2605
emp_length               11
home_ownership            5
verification_status       3
issue_d                  43
loan_status               4
pymnt_plan                1
purpose                  14
title                  2287
zip_code                609
addr_state               50
earliest_cr_line        381
revol_util              954
initial_list_status       1
last_pymnt_d             96
last_credit_pull_d      105
application_type          1
dtype: int64

String type columns containing values that are less than 50% unique:

term
int_rate
grade
sub_grade
emp_length
home_ownership
verification_status
issue_d
loan_status
pymnt_plan
purpose
zip_code
addr_state
earliest_cr_line
revol_util
initial_list_status
last_pymnt_d
last_credit_pull_d
application_type

Floating type columns with no missing values:

member_id
loan_amnt
funded_amnt
funded_amnt_inv
installment
annual_inc
dti
delinq_2yrs
inq_last_6mths
open_acc
pub_rec
revol_bal
total_acc
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_amnt
collections_12_mths_ex_med
policy_code
acc_now_delinq
chargeoff_within_12_mths
delinq_amnt
pub_rec_bankruptcies
tax_liens

==================================================

Num. of numeric type columns: 30

Num. of string type columns: 22

Unique values in each string type column:

id                     538
term                     1
int_rate                86
grade                    7
sub_grade               35
emp_title              477
emp_length              11
home_ownership           4
verification_status      1
issue_d                  9
loan_status              2
pymnt_plan               1
purpose                 13
title                  462
zip_code               267
addr_state              42
earliest_cr_line       218
revol_util             379
initial_list_status      1
last_pymnt_d            45
last_credit_pull_d      89
application_type         1
dtype: int64

String type columns containing values that are less than 50% unique:

term
int_rate
grade
sub_grade
emp_length
home_ownership
verification_status
issue_d
loan_status
pymnt_plan
purpose
zip_code
addr_state
earliest_cr_line
initial_list_status
last_pymnt_d
last_credit_pull_d
application_type

Floating type columns with no missing values:

member_id
loan_amnt
funded_amnt
funded_amnt_inv
installment
annual_inc
dti
delinq_2yrs
inq_last_6mths
open_acc
pub_rec
revol_bal
total_acc
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_amnt
collections_12_mths_ex_med
policy_code
acc_now_delinq
chargeoff_within_12_mths
delinq_amnt
pub_rec_bankruptcies
tax_liens

==================================================

Total memory usage (MB) = 66.2153730392456